// Director API, shared endpoints

DIRECTOR_THREAT_NULL = -1
DIRECTOR_THREAT_HEAT = 0
DIRECTOR_THREAT_ALERT = 1
DIRECTOR_THREAT_COMBAT = 2

// Not used on the server. Leaving it here just for you! :3
DIRECTOR_LAYER_TABLE = {
	DIRECTOR_THREAT_HEAT,
	DIRECTOR_THREAT_ALERT,
	DIRECTOR_THREAT_COMBAT
}
